# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Times',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_time', models.CharField(max_length=20)),
                ('link_time', models.CharField(max_length=20)),
                ('email_time', models.CharField(max_length=30)),
            ],
        ),
    ]
