# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0002_auto_20170418_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='time',
            old_name='email_time',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='time',
            old_name='link_time',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='time',
            old_name='nome_time',
            new_name='nome',
        ),
    ]
