# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0003_auto_20170419_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='time',
            old_name='link',
            new_name='gitlab_team_link',
        ),
        migrations.AddField(
            model_name='time',
            name='github_link',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='time',
            name='slacker_link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
