# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0004_auto_20170423_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='gitlab_team_link',
            field=models.CharField(max_length=100),
        ),
    ]
