# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0005_auto_20170423_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='time',
            old_name='slacker_link',
            new_name='slack_link',
        ),
    ]
